"""
Django settings for techcrunch_scraper project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# TODO: if you downloaded this project you should do the following:
# TODO: - Use sample_settings.py to create your own local settings
from .local_settings import CELERY_LOCAL_TIMEZONE, CELERY_LOCAL_BROKER_URL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uq0bqlm=i_3k_ri(+f#ugmmkh@p&yy7)1xksd-erk7w%070km4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Local
    'techcrunch.apps.TechcrunchConfig',

    # Trusted Apps
    'django_celery_beat',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'techcrunch_scraper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'template')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'techcrunch_scraper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Number of characters to display summary
BRIEF_CHAR_COUNT_TITLE = 15
BRIEF_CHAR_COUNT_CONTENT = 45

DEFAULT_SEARCH_PAGE_COUNT_TECH_CRUNCH = 1
MAXIMUM_SEARCH_PAGE_COUNT_TECH_CRUNCH = 100

DEFAULT_POST_COUNT_TECH_CRUNCH = 20
DEFAULT_CATEGORY_COUNT_UPDATE = 40
# ---URLS---

EMBED_TRUE = '&_embed=true'
ENVELOPE_TRUE = '&_envelope=true'
EMBED_FALSE = ''
ENVELOPE_FALSE = ''

# BASE URLS
BASE_URL = 'https://www.techcrunch.com'
WP_JSON_BASE_URL = BASE_URL + '/wp-json'


# ***SEARCH***
SEARCH_URL_TECH_CRUNCH = (
    'https://search.techcrunch.com/search'
    '?'
    'p={keyword}'
    '&b={page}1'
)
POST_BY_CATEGORY_URL_TECH_CRUNCH = (
    WP_JSON_BASE_URL
    + '/wp/v2/posts'
      '?'
      'categories={category_id}'
      '&per_page={per_page}'
      '&page={page}'
      '{envelope}'
      '{embed}'
)


# ***CATEGORY***
# envelope: get Meta data about this json | (true/false)
ALL_CATEGORIES_JSON_URL_TECH_CRUNCH = (
    WP_JSON_BASE_URL + '/wp/v2/categories'
                       '?'
                       'per_page={count}'
                       '{envelope}'
)
CATEGORY_JSON_URL_TECH_CRUNCH = (
    WP_JSON_BASE_URL + '/wp/v2/categories/{id}'
)


# ***POST***
# envelope: get Meta data about this json | (true/false)
# embed: get all data about author and category in "_embedded" tag | (true/false)
POST_JSON_URL_BY_SLUG_TECH_CRUNCH = (
    WP_JSON_BASE_URL + '/wp/v2/posts'
                       '?'
                       'slug={slug}'
                       '{embed}'
                       '{envelope}'
)
POST_JSON_URL_BY_ID_TECH_CRUNCH = (
    WP_JSON_BASE_URL + '/wp-json/wp/v2/posts/{id}'
                       '?'
                       '{embed}'
                       '{envelope}'
)


# ***USER***
USER_JSON_URL_BY_SLUG_TECH_CRUNCH = (
    WP_JSON_BASE_URL + '/wp-json/tc/v1/users'
                       '?'
                       'slug={slug}'
)
USER_JSON_URL_BY_ID_TECH_CRUNCH = (
    WP_JSON_BASE_URL + '/wp-json/tc/v1/users/{id}'
)

# Celery configurations
# Celery Configuration Options
CELERY_BROKER_URL = CELERY_LOCAL_BROKER_URL
CELERY_TIMEZONE = CELERY_LOCAL_TIMEZONE
CELERY_TASK_TIME_LIMIT = 60 * 60

CELERY_RESULT_BACKEND = 'django-db'
# CELERY_CACHE_BACKEND = 'django-cache'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
