# Generated by Django 4.2 on 2024-04-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategorynewpost',
            name='is_scraped',
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dailysearch',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
