# Generated by Django 4.2 on 2024-04-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0002_failedsearchedposts_imagepost_postdailysearch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedpostscategory',
            old_name='scraped_posts',
            new_name='scraped_post',
        ),
    ]
