# Generated by Django 4.2 on 2024-04-07 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0002_failedsearchedposts_imagepost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post_count',
        ),
    ]
