# Generated by Django 4.2 on 2024-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0003_remove_category_post_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='tech_crunch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
