# Generated by Django 4.2 on 2024-04-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techcrunch', '0003_rename_scraped_posts_scrapedpostscategory_scraped_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dailysearch',
            options={'verbose_name': 'Daily Search', 'verbose_name_plural': 'Daily Searches'},
        ),
        migrations.AlterModelOptions(
            name='failedcategorynewposts',
            options={'verbose_name': 'Failed Category New Post', 'verbose_name_plural': 'Failed Category New Posts'},
        ),
        migrations.AlterModelOptions(
            name='failedsearchedposts',
            options={'verbose_name': 'Failed Searched Post', 'verbose_name_plural': 'Failed Searched Posts'},
        ),
        migrations.AlterModelOptions(
            name='imagefile',
            options={'verbose_name': 'Image File', 'verbose_name_plural': 'Image Files'},
        ),
        migrations.AlterModelOptions(
            name='imagepost',
            options={'verbose_name': 'Image Post', 'verbose_name_plural': 'Images Post'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name': 'Post Category', 'verbose_name_plural': 'Post Categories'},
        ),
        migrations.AlterModelOptions(
            name='postdailysearch',
            options={'verbose_name': 'Post Daily Search', 'verbose_name_plural': 'Post Daily Searches'},
        ),
        migrations.AlterModelOptions(
            name='scrapedposts',
            options={'verbose_name': 'Scraped Post', 'verbose_name_plural': 'Scraped Posts'},
        ),
        migrations.AlterModelOptions(
            name='scrapedpostscategory',
            options={'verbose_name': 'Scraped Post Category', 'verbose_name_plural': 'Scraped Posts Categories'},
        ),
        migrations.AlterModelOptions(
            name='searchedkeyword',
            options={'verbose_name': 'Searched Keyword', 'verbose_name_plural': 'Searched Keywords'},
        ),
        migrations.AlterModelOptions(
            name='searchedpostbykeyword',
            options={'verbose_name': 'Searched Post By Keyword', 'verbose_name_plural': 'Searched Post By Keywords'},
        ),
    ]
